### PR TITLE
Further reduce io_uring syscalls

### PR DESCRIPTION
**Pull request by njhill**
Motivation

IOUringEventLoop can be streamlined to further reduce io_uring_enter calls

Modification

- Don't prepare to block-wait until all available work is exhausted
- Combine submission with GETEVENTS

Result

Hopefully faster

### CODE REVIEW

**Review by franz1981 — APPROVED** [review]

**Comment by 1Jo1** [comment]
@njhill really good idea 👍

**Comment by njhill** [comment]
@normanmaurer @1Jo1 now rebased.

Thanks @1Jo1 ... I know you have some latency concerns about deferring the submits longer but my hope is that we can be quite aggressive with that since the cost of event loop iterations should generally be negligible relative to a syscall.

**Comment by 1Jo1** [comment]
@njhill thats true, no worries we can merge it, I will do some latency tests tomorrow

btw some tests failing:

- IOUringCompositeBufferGatheringWriteTest.testSingleCompositeBufferWrite- 
- IOUringEventLoopTest>AbstractSingleThreadEventLoopTest.gracefulShutdownAfterStart
- IOUringEventLoopTest>AbstractSingleThreadEventLoopTest.shutdownGracefullyBeforeStart
- IOUringEventLoopTest>AbstractSingleThreadEventLoopTest.shutdownGracefullyZeroQuietBeforeStart
- OUringSocketSslSessionReuseTest.testSslSessionReuse:

**Comment by normanmaurer** [comment]
Please ignore `IOUringSocketSslSessionReuseTest.testSslSessionReuse` for now... I will have a look.

**Comment by normanmaurer** [comment]
I will test this with the benchmark later today .

**Comment by njhill** [comment]
Thanks @normanmaurer that would be great. I just pushed a commit to fix the shutdown related failures, though there still appears to be some kind of flakiness in the Ssl tests, not sure if that's related.

**Comment by njhill** [comment]
@normanmaurer I rebased and made a small change, would be interested to hear benchmark results :)

**Comment by normanmaurer** [comment]
@njhill performance makes no difference in the echo benchmark to before...

**Comment by normanmaurer** [comment]
That said this doesn't mean it is not an improvement.... it just doesn't make any difference in this benchmark :)

**Comment by franz1981** [comment]
async profile it :)
If the liburing stuff is being compiled with debug symbols and frame
pointer we can have some fun there :P

Il sab 5 set 2020, 19:56 Norman Maurer <notifications@github.com> ha
scritto:

**Comment by normanmaurer** [comment]
@njhill  can you please open the PR against https://github.com/netty/netty/tree/io-uring ? We will continue the development in the main netty project from now on (as GSOC is over)

**Comment by normanmaurer** [comment]
@franz1981 btw we don't use liburing ... we use the low level API provided by the kernel directly ;)

**Comment by njhill** [comment]
Moved to https://github.com/netty/netty/pull/10542

**Pull request closed without merging**
