### PR TITLE
Use IOSQE_ASYNC flag when submitting

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

At least in the throughput benchmarks it has shown that IOSQE_ASYNC
gives a lot of performance improvements. Lets enable it by default for
now and maybe make it configurable in the future

Modifications:

Use IOSEQ_ASYNC

Result:

Better performance

### CODE REVIEW

**Comment by normanmaurer** [comment]
/cc @njhill @franz1981 @chrisvest ... 

Special thanks to @chrisvest for the suggestion.

NIO as baseline:

```
norman@ubuntu-dev:~/Apps/rust_echo_bench$ ./run.sh 9090
Linux ubuntu-dev 5.8.5-iouringfix+ #2 SMP Thu Sep 3 12:58:01 CEST 2020 x86_64 x86_64 x86_64 GNU/Linux
pid 126331's current affinity list: 0
pid 126331's new affinity list: 0
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/echo_bench --address 'localhost:9090' --number 500 --duration 30 --length 128`
Benchmarking: localhost:9090
500 clients, running 128 bytes, 30 sec.
Speed: 78744 request/sec, 78744 response/sec
Requests: 2362321
Responses: 2362320
```

Before this PR:

```
norman@ubuntu-dev:~/Apps/rust_echo_bench$ ./run.sh 8080
Linux ubuntu-dev 5.8.5-iouringfix+ #2 SMP Thu Sep 3 12:58:01 CEST 2020 x86_64 x86_64 x86_64 GNU/Linux
pid 138209's current affinity list: 0
pid 138209's new affinity list: 0
   Finished release [optimized] target(s) in 0.00s
    Running `target/release/echo_bench --address 'localhost:8080' --number 500 --duration 30 --length 128`
Benchmarking: localhost:8080
500 clients, running 128 bytes, 30 sec.
Speed: 124256 request/sec, 124256 response/sec
Requests: 3727709
Responses: 3727708
```

With this change:

```
norman@ubuntu-dev:~/Apps/rust_echo_bench$ ./run.sh 8080
Linux ubuntu-dev 5.8.5-iouringfix+ #2 SMP Thu Sep 3 12:58:01 CEST 2020 x86_64 x86_64 x86_64 GNU/Linux
pid 143850's current affinity list: 0
pid 143850's new affinity list: 0
    Finished release [optimized] target(s) in 0.00s
     Running `target/release/echo_bench --address 'localhost:8080' --number 500 --duration 30 --length 128`
Benchmarking: localhost:8080
500 clients, running 128 bytes, 30 sec.
Speed: 244279 request/sec, 244279 response/sec
Requests: 7328385
Responses: 7328377
```

🔥

**Comment by 1Jo1** [comment]
my test:

Nio:

```
cargo run --release -- --address "127.0.0.1:8080" --number 500 --duration 30 --length 128
    Finished release [optimized] target(s) in 0.00s
     Running `target/release/echo_bench --address '127.0.0.1:8080' --number 500 --duration 30 --length 128`
Benchmarking: 127.0.0.1:8080
500 clients, running 128 bytes, 30 sec.

Speed: 139344 request/sec, 139344 response/sec
Requests: 4180346
Responses: 4180346
```


io_uring with flag:

```
cargo run --release -- --address "127.0.0.1:8080" --number 500 --duration 30 --length 128 
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/echo_bench --address '127.0.0.1:8080' --number 500 --duration 30 --length 128`
Benchmarking: 127.0.0.1:8080
500 clients, running 128 bytes, 30 sec.

Speed: 323870 request/sec, 323870 response/sec
Requests: 9716123
Responses: 9716114
```

**Comment by njhill** [comment]
Nice one @chrisvest @normanmaurer!

This is interesting and slightly surprising to me since I assumed most of the submissions would be non-blocking. I wonder if setting this selectively based on the operation could help even more (i.e. just for the polls)?

**Comment by normanmaurer** [comment]
@njhill i need to do some more testing and research here 🤷‍♂️

**Comment by normanmaurer** [comment]
Unfortunally it seems like this one can cause some problems with a few kernels:

https://lore.kernel.org/io-uring/6428c1ee0234105d18c5e3e88aa00c57@nickhill.org/T/#t

But a fix is already proposed.

**Comment by njhill** [comment]
@normanmaurer fyi simple workaround for now is to change it to:
```java
        PlatformDependent.putByte(sqe + SQE_FLAGS_FIELD,
            (byte) (op != Native.IORING_OP_WRITEV ? Native.IOSQE_ASYNC : 0));
```

**Comment by normanmaurer** [comment]
@njhill yep thanks... I am about to compile a new kernel with the proposed fix and see if this fixes it :)

**Comment by normanmaurer** [comment]
For the record here is the proposed fix:

https://lore.kernel.org/io-uring/d8404079-fe7e-3f42-4460-22328b12b0fa@kernel.dk/

**Comment by normanmaurer** [comment]
@njhill at the end I decided to just do a PR with your workaround for now to make it easier for people to develop until a fix is merged into the kernel: https://github.com/1Jo1/netty/pull/36

**Comment by 1Jo1** [comment]
> This is interesting and slightly surprising to me since I assumed most of the submissions would be non-blocking. I wonder if setting this selectively based on the operation could help even more (i.e. just for the polls)?

@njhill yeah I'm quite surprised too, I'm guessing writeev/write and read operation are faster, it seems to be that `IOSQE_ASYNC` skips the arm handler and the operations will be executed in async threads from the start, poll operation I will test that later :)

**Pull request merged**
